// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7etiSRVRE-asG-Uez6cmOoM7KIr2EaKQ',
    appId: '1:630452083591:web:65ff7b918c12bb71eb1122',
    messagingSenderId: '630452083591',
    projectId: 'fluutterstore',
    authDomain: 'fluutterstore.firebaseapp.com',
    storageBucket: 'fluutterstore.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDff9XU2agKguV4hD-L4cubLqMeAj1R5cI',
    appId: '1:630452083591:android:8d7283aa2d23ba2ceb1122',
    messagingSenderId: '630452083591',
    projectId: 'fluutterstore',
    storageBucket: 'fluutterstore.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7etiSRVRE-asG-Uez6cmOoM7KIr2EaKQ',
    appId: '1:630452083591:web:f88e974ac5b6ffdfeb1122',
    messagingSenderId: '630452083591',
    projectId: 'fluutterstore',
    authDomain: 'fluutterstore.firebaseapp.com',
    storageBucket: 'fluutterstore.firebasestorage.app',
  );
}
